#!/usr/bin/env bash

# Tag a release that will be built with Github Actions. The version is
# read from 'postgrest.cabal'.

version="$(grep -oP '^version:\s*\K.*' postgrest.cabal)"

echo "Tagging version v$version"
git tag -f "v$version"

echo "Pushing tag..."
git push -f origin "refs/tags/v$version"
