set -e

stack build --resolver lts-3.0
stack build --resolver lts-4.0
stack build --resolver lts-5.0
stack build --resolver lts-6.0
stack build --resolver lts-7.0
stack build --resolver lts-7.1
stack build --resolver lts-7.2
stack build --resolver lts-7.3
stack build --resolver lts-7.4
stack build --resolver lts-7.5
stack build --resolver lts-7.6
stack build --resolver lts-7.7
stack build --resolver lts-7.8
stack build --resolver lts-7.9
stack build --resolver lts-7.10
stack build --resolver lts-7.11
stack build --resolver lts-7.12
stack build --resolver lts-7.13
stack build --resolver lts-7.14
stack build --resolver lts-7.15
stack build --resolver lts-7.16
stack build --resolver lts-8.0
stack build --resolver lts-8.1
stack build --resolver lts-8.2
stack build --resolver lts-8.3
stack build --resolver lts-8.4
stack build --resolver lts-8.5
stack build --resolver lts-8.6
stack build --resolver lts-8.7
stack build --resolver lts-8.8
stack build --resolver lts-8.9
stack build --resolver lts-8.10
stack build --resolver lts-8.11
stack build --resolver lts-8.12
stack build --resolver lts-8.13
stack build --resolver lts-9.0
stack build --resolver lts-9.1
stack build --resolver lts-9.2
stack build --resolver lts-9.3
stack build --resolver lts-9.4
stack build --resolver lts-9.5
stack build --resolver lts-9.6
stack build --resolver lts-9.7
stack build --resolver lts-9.8
stack build --resolver lts-9.9
stack build --resolver lts-9.10
stack build --resolver lts-9.11
stack build --resolver lts-9.12
stack build --resolver lts-9.13
stack build --resolver lts-9.14
stack build --resolver lts-9.15
stack build --resolver lts-9.16
stack build --resolver lts-9.17
stack build --resolver lts-9.18
stack build --resolver lts-9.19
stack build --resolver lts-9.20
stack build --resolver lts-10.0
stack build --resolver lts-10.1
stack build --resolver lts-10.2
stack build --resolver lts-11.0
stack build --resolver lts-11.1
stack build --resolver lts-11.2
stack build --resolver lts-11.3
stack build --resolver lts-11.4
stack build --resolver lts-11.5
stack build --resolver lts-11.6
stack build --resolver lts-11.7
stack build --resolver lts-11.8
stack build --resolver lts-11.10
stack build --resolver lts-11.11
stack build --resolver lts-11.12
stack build --resolver lts-11.13
stack build --resolver lts-12.0
stack build --resolver lts-12.1
stack build --resolver lts-12.2
stack build --resolver lts-12.3
stack build --resolver lts-12.4
stack build --resolver lts-12.5
stack build --resolver lts-12.6
stack build --resolver lts-12.7
stack build --resolver lts-12.8
stack build --resolver lts-12.9
stack build --resolver lts-12.10
stack build --resolver lts-12.11
stack build --resolver lts-12.12
stack build --resolver lts-12.13
stack build --resolver lts-12.14
stack build --resolver lts-12.16
stack build --resolver lts-12.17
stack build --resolver lts-12.18
stack build --resolver lts-12.19
stack build --resolver lts-12.20
stack build --resolver lts-12.21
stack build --resolver lts-13.0
stack build --resolver lts-13.1
stack build --resolver lts-13.2
stack build --resolver lts-13.3
stack build --resolver lts-13.4
stack build --resolver lts-13.5
stack build --resolver lts-13.6
stack build --resolver lts-13.7
stack build --resolver lts-13.8
stack build --resolver lts-13.9
stack build --resolver lts-13.10
stack build --resolver lts-13.11
stack build --resolver lts-13.12
stack build --resolver lts-13.13
stack build --resolver lts-13.14
stack build --resolver lts-13.15
stack build --resolver lts-13.16
stack build --resolver lts-13.17
stack build --resolver lts-13.18
stack build --resolver lts-13.19
stack build --resolver lts-13.20
stack build --resolver lts-13.21
stack build --resolver lts-13.22
stack build --resolver lts-13.23
stack build --resolver lts-13.24
stack build --resolver lts-13.25
stack build --resolver lts-13.26
stack build --resolver lts-14.0
stack build --resolver lts-14.1
stack build --resolver lts-14.2
stack build --resolver lts-14.3
stack build --resolver lts-14.4
stack build --resolver lts-14.5
stack build --resolver lts-14.6
stack build --resolver lts-14.7
stack build --resolver lts-14.8
stack build --resolver lts-14.9
stack build --resolver lts-14.10
stack build --resolver lts-14.11
stack build --resolver lts-14.12
stack build --resolver lts-14.13
stack build --resolver lts-14.14
