freebsd_instance:
  image: freebsd-12-1-release-amd64

build_task:
  # caches the freebsd package downloads
  # saves probably just a couple of seconds, but hey...
  pkg_cache:
    folder: /var/cache/pkg

  install_script:
    - pkg install -y postgresql95-client ghc hs-cabal-install
  
  # cache the hackage index file and downloads which are
  # cabal v2-update downloads an incremental update, so we don't need to keep this up2date
  packages_cache:
    # warning: don't use ~/.cabal here, this will break the cache
    folder: /.cabal/packages
    reupload_on_changes: false

  # cache the dependencies built by cabal
  # they have to be uploaded on every change to make the next build fast
  store_cache:
    # warning: don't use ~/.cabal here, this will break the cache
    folder: /.cabal/store
    fingerprint_script: cat postgrest.cabal
    reupload_on_changes: true

  build_script:
    - cabal v2-update
    - cabal v2-build

  binaries_artifacts:
    path: "dist-newstyle/build/x86_64-freebsd/ghc-8.6.5/postgrest-7.0.1/x/postgrest/build/postgrest/*"
