freebsd_instance:
  image_family: freebsd-14-0

build_task:
  # Don't change this name without adjusting .github/workflows/ci.yaml
  name: Build FreeBSD (Stack)
  install_script: pkg install -y postgresql13-client hs-stack git

  stack_cache:
    folders: /.stack
    fingerprint_script: cat postgrest.cabal stack.yaml.lock
    reupload_on_changes: false

  build_script: stack build -j 1 --local-bin-path . --copy-bins
  bin_artifacts:
    path: postgrest
