codecov:
  branch: master
  require_ci_to_pass: false

comment: false

coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0%
        only_pulls: false
    patch:
      default:
        target: auto
        threshold: 0%
        only_pulls: true
