resolver: nightly-2017-01-31
extra-deps:
  - Ranged-sets-0.3.0
  - hasql-pool-0.4.1
  - hasql-transaction-0.5
  - optparse-applicative-0.13.0.0
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-identities -fno-warn-redundant-constraints
nix:
  packages: [postgresql, zlib]
