resolver: lts-7.4
extra-deps:
  - Ranged-sets-0.3.0
  - hasql-pool-0.4.1
  - hasql-transaction-0.5
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-identities -fno-warn-redundant-constraints
nix:
  packages: [postgresql, zlib]
