resolver: lts-22.44 # 2025-05-02, GHC 9.6.7

nix:
  packages:
    - libpq
    - pkg-config
    - zlib
  # disable pure by default so that the test environment can be passed
  pure: false

extra-deps:
  - configurator-pg-0.2.11
  - fuzzyset-0.2.4
  - hasql-pool-1.0.1
  - jose-jwt-0.10.0
  - postgresql-libpq-0.10.1.0
  - streaming-commons-0.2.3.1

  # fix build with GCC 15-ish; https://github.com/gregorycollins/hashtables/issues/98 for details
  - hashtables-1.4.2@sha256:4940cab94a15d469845ccf5225f9cb3d354c15e8127ebb58425c8b681f7721d9,10386
