resolver: lts-23.27 # 2025-07-06, GHC 9.8.4

nix:
  packages:
    - libpq
    - pkg-config
    - zlib
  # disable pure by default so that the test environment can be passed
  pure: false

extra-deps:
  - fuzzyset-0.2.4
  - hasql-1.6.4.4
  - hasql-dynamic-statements-0.3.1.5
  - hasql-implicits-0.1.1.3
  - hasql-notifications-0.2.2.2
  - hasql-pool-1.0.1
  - hasql-transaction-1.1.0.1
  - postgresql-binary-0.13.1.3

allow-newer: true
allow-newer-deps:
  - fuzzyset
  - hasql
