resolver: lts-9.6
extra-deps:
  - configurator-ng-0.0.0.1
  - critbit-0.2.0.0
  - hjsonpointer-1.1.1
  - hjsonschema-1.5.0.1
  - Ranged-sets-0.3.0
  - protolude-0.2.2
  - hasql-1.3
  - hasql-pool-0.5
  - hasql-transaction-0.7
  - text-builder-0.5.1.1
  - jose-0.7.0.0
  - postgresql-libpq-0.9.4.1
  - http-types-0.12.3
  - wai-middleware-static-0.8.2
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-identities -fno-warn-redundant-constraints
nix:
  packages: [postgresql, zlib]
# only added because of hjsonschema conflict with http-types
# once hjsonschema upper bounding on http-types is solved it can be removed
allow-newer: true
