resolver: lts-6.2
extra-deps:
  - Ranged-sets-0.3.0
  - bytestring-tree-builder-0.2.7
  - hasql-0.19.12
  - hasql-pool-0.4.1
  - hasql-transaction-0.4.5
  - jwt-0.7.2
  - postgresql-binary-0.9.0.1
  - binary-parser-0.5.2
  - contravariant-extras-0.3.2
  - placeholders-0.1
  - postgresql-error-codes-1
  - success-0.2.6
  - tuple-th-0.2.5
  - wai-cors-0.2.5
  - cryptohash-sha256-0.11.100.0
  - hackage-security-0.5.2.1
  - unordered-containers-0.2.7.1
  - insert-ordered-containers-0.1.0.1
  - swagger2-2.1
  # - hjsonschema-0.10.0.2
  - hjsonpointer-0.3.0.1
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-identities

packages:
- .
- location:
    git: https://github.com/hudayou/hjsonschema.git
    commit: 2dccf1b738920e4b1bea50804d2f1d546ab1b210
  extra-dep: true
