resolver: lts-9.6
extra-deps:
  - configurator-ng-0.0.0.1
  - critbit-0.2.0.0
  - hjsonpointer-1.1.1
  - hjsonschema-1.5.0.1
  - Ranged-sets-0.3.0
  - protolude-0.2.2
  - hasql-1.1
  - hasql-pool-0.4.3
  - hasql-transaction-0.5.2
  - jose-0.7.0.0
  - postgresql-libpq-0.9.4.1
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-identities -fno-warn-redundant-constraints
nix:
  packages: [postgresql, zlib]
