resolver: lts-21.7 # 2023-08-14, GHC 9.4.5

nix:
  packages:
    - pcre
    - pkgconfig
    - postgresql
    - zlib
  # disable pure by default so that the test enviroment can be passed
  pure: false

extra-deps:
  - configurator-pg-0.2.7
  - fuzzyset-0.3.1
  - hasql-notifications-0.2.0.6
  - hasql-pool-0.10
  - megaparsec-9.2.2
  - postgresql-libpq-0.10.0.0
  - github: develop7/hs-opentelemetry
    commit: ec5a87729ad3ad99c59fdcdfa754bafc87edac57
    subdirs:
      - sdk
      - api
      - propagators/b3
      - propagators/w3c
      - exporters/otlp
      - utils/exceptions
      - instrumentation/wai
      - otlp
  - unix-compat-0.7.1@sha256:bd5bb4e04b2ed707f3e3466470a452354310389506cf0a7a73bf10e4d533f6d1,3619
  - thread-utils-context-0.3.0.4@sha256:e763da1c6cab3b6d378fb670ca74aa9bf03c9b61b6fcf7628c56363fb0e3e71e,1671
  - thread-utils-finalizers-0.1.1.0@sha256:24944b71d9f1d01695a5908b4a3b44838fab870883114a323336d537995e0a5b,1381
