resolver: lts-21.7 # 2023-08-14, GHC 9.4.5

nix:
  packages:
    - pcre
    - pkgconfig
    - postgresql
    - zlib
  # disable pure by default so that the test enviroment can be passed
  pure: false

extra-deps:
  - configurator-pg-0.2.7
  - fuzzyset-0.3.1
  - hasql-notifications-0.2.1.0
  - hasql-pool-0.10
  - megaparsec-9.2.2
  - postgresql-libpq-0.10.0.0
