resolver: lts-9.0
extra-deps:
  - configurator-ng-0.0.0.1
  - critbit-0.2.0.0
  - hasql-pool-0.4.1
  - hjsonpointer-1.1.1
  - hjsonschema-1.5.0.1
  - jose-0.5.0.3
  - Ranged-sets-0.3.0
  - protolude-0.2
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-identities -fno-warn-redundant-constraints
nix:
  packages: [postgresql, zlib]
