resolver: lts-22.44 # 2025-05-02, GHC 9.6.7

nix:
  packages:
    - libpq
    - libpq.pg_config
    - pkg-config
    - zlib

extra-deps:
  - fuzzyset-0.2.4
  - hasql-pool-1.0.1
  - jose-jwt-0.10.0
  - postgresql-libpq-0.10.1.0
