resolver: lts-22.21 # 2024-05-06, GHC 9.6.5

nix:
  packages:
    - pcre
    - pkgconfig
    - postgresql
    - zlib
  # disable pure by default so that the test enviroment can be passed
  pure: false

extra-deps:
  - fuzzyset-0.2.4
  - hasql-notifications-0.2.2.0
  - hasql-pool-1.0.1
