resolver: lts-10.7
extra-deps:
  - configurator-ng-0.0.0.1
  - critbit-0.2.0.0
  - hjsonschema-1.5.0.1
  - Ranged-sets-0.3.0
ghc-options:
  postgrest: -O2 -Werror -Wall -fwarn-identities -fno-warn-redundant-constraints
nix:
  packages: [postgresql, zlib]
