resolver: lts-24.37 # 2026-04-15, GHC 9.10.3

nix:
  packages:
    - libpq
    - libpq.pg_config
    - pkg-config
    - zlib

extra-deps:
  - configurator-pg-0.2.11
  - fuzzystrmatch-pg-0.1.0.0
  - hasql-1.6.4.4
  - hasql-dynamic-statements-0.3.1.5
  - hasql-implicits-0.1.1.3
  - hasql-notifications-0.2.2.2
  - hasql-pool-1.0.1
  - hasql-transaction-1.1.0.1
  - http-semantics-0.4.0
  - http2-5.4.0
  - postgresql-binary-0.13.1.3
  - text-builder-0.6.10
  - text-builder-dev-0.3.10
  - warp-3.4.13

allow-newer: true
allow-newer-deps:
  - fuzzystrmatch-pg
  - hasql
