cabal-version:      3.0
name:               restart
version:            0.0.0.0
synopsis:           Restartable process runner
description:        Small framework for applications that can restart by replacing their own process.
license:            MIT
license-file:       LICENSE
author:             PostgREST contributors
maintainer:         PostgREST contributors
category:           System
build-type:         Simple

library
  default-language:   Haskell2010
  default-extensions: OverloadedStrings
                      NoImplicitPrelude
                      NumericUnderscores
  hs-source-dirs:     src/common
  exposed-modules:    System.Process.Restart
  other-modules:      System.Process.Restart.Impl
                      System.Process.Restart.Shared
  build-depends:      base                      >= 4.9 && < 4.22
                    , bytestring                >= 0.10.8 && < 0.13
                    , containers                >= 0.5.7 && < 0.8
                    , protolude                 >= 0.3.1 && < 0.4
  ghc-options:        -j -Werror -Wall -fwarn-identities
                      -fno-spec-constr -optP-Wno-nonportable-include-path

  if os(windows)
    hs-source-dirs:
      src/windows
  else
    hs-source-dirs:
      src/posix
    build-depends:    network                   >= 2.6 && < 3.3
                    , text                      >= 1.2.2 && < 2.2
                    , unix
