stgrest:
  image: pg_local
  ports:
    - "3000:3000"
  links:
    - postgres:postgres
  environment:
    PGRST_DB_URI: postgres://app_user:password@postgres:5432/app_db
    PGRST_DB_SCHEMA: public
    PGRST_DB_ANON_ROLE: app_user

postgres:
  image: postgres:9
  ports:
    - "5432:5432"
  environment:
    POSTGRES_DB: postgrest_test
    POSTGRES_USER: postgrest_test
    POSTGRES_PASSWORD: password
