module Feature.OpenApi.RootSpec where

import Network.HTTP.Types

import Test.Hspec          hiding (pendingWith)
import Test.Hspec.Wai
import Test.Hspec.Wai.JSON

import PostgREST.Config                  (AppConfig (..))
import PostgREST.SchemaCache.Identifiers (QualifiedIdentifier (..))

import Protolude  hiding (get)
import SpecHelper

spec :: SpecWithConfig
spec withConfig = withConfig (baseCfg { configDbRootSpec = Just $ QualifiedIdentifier mempty "root" }) $
  describe "root spec function" $ do
    it "accepts application/openapi+json" $ do
      request methodGet "/"
        [("Accept","application/openapi+json")] "" `shouldRespondWith`
        [json|{
           "swagger": "2.0",
           "info": {"title": "PostgREST API", "description": "This is a dynamic API generated by PostgREST"}
          }|]
        { matchHeaders = ["Content-Type" <:> "application/openapi+json; charset=utf-8"] }

    it "accepts application/json" $ do
      request methodGet "/"
        [("Accept","application/json")] "" `shouldRespondWith`
        [json|{
           "swagger": "2.0",
           "info": {"title": "PostgREST API", "description": "This is a dynamic API generated by PostgREST"}
          }|]
        { matchHeaders = ["Content-Type" <:> "application/json; charset=utf-8"] }
