#!/usr/bin/env bash

set -euo pipefail

dir="$(dirname "$0")"

script="
   \set ON_ERROR_STOP on

   prepare dbstructure(name[]) as
     $(cat "$dir"/query.sql)
     ;

   explain (analyze, costs, verbose, buffers, format json) execute dbstructure(array['$1']);
"

echo "$script" | psql -qAt
