#!/usr/bin/env bash

set -euo pipefail

dir="$(dirname "$0")"

tempfile="$(mktemp)"

trap 'rm $tempfile' exit

script="
  \set ON_ERROR_STOP on

  prepare dbstructure(name[]) as
    $(cat "$dir"/query.sql)
    ;

  \timing on

  \o $tempfile
  execute dbstructure(array['$1']);
"

echo "$script" | psql -q

sed -n 3p < "$tempfile" | jq "$2"

sed -n 3p < "$tempfile" | jq . | wc -l
