# Misspelled relations
GET http://postgrest/actoxs?actor=eq.1
Prefer: tx=commit

# Misspelled relations on embeds
GET http://postgrest/actors?select=*,rolws(*,films(*))
Prefer: tx=commit

# Misspelled function names
GET http://postgrest/rpc/call_em_x?name=John
Prefer: tx=commit

# Permission denied errors
GET http://postgrest/actors_1
Prefer: tx=commit
