GET http://postgrest/

HEAD http://postgrest/actors?actor=eq.1

GET http://postgrest/actors?select=*,roles(*,films(*))
Accept: application/vnd.pgrst.sql

POST http://postgrest/films?columns=id,title
Accept: application/vnd.pgrst.sql
@post.json

POST http://postgrest/films?columns=id,title,year,runtime,genres,director,actors,plot,posterUrl
Accept: application/vnd.pgrst.sql
# this bulk.json was obtained from https://github.com/erik-sytnyk/movies-list/blob/master/db.json
@bulk.json

PUT http://postgrest/actors?actor=eq.1&columns=name
Accept: application/vnd.pgrst.sql
@put.json

PATCH http://postgrest/actors?actor=eq.1
Accept: application/vnd.pgrst.sql
@patch.json

DELETE http://postgrest/roles
Accept: application/vnd.pgrst.sql

GET http://postgrest/rpc/call_me?name=John
Accept: application/vnd.pgrst.sql

POST http://postgrest/rpc/call_me
Accept: application/vnd.pgrst.sql
@rpc.json

OPTIONS http://postgrest/actors

# Misspelled relations
GET http://postgrest/actoxs?actor=eq.1

# Misspelled relations on embeds
GET http://postgrest/actors?select=*,rolws(*,films(*))

# Misspelled function names
GET http://postgrest/rpc/call_me_x?name=John

# Permission denied errors
GET http://postgrest/actors_1
