name: Linkcheck

on:
  pull_request: # Temporarily test using PR, remove this before merge
    branches:
      - main
  schedule:
    - cron: '1 2 * * 3'
  workflow_dispatch:

permissions:
  issues: write

jobs:
  linkcheck:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
    - name: Setup Nix Environment
      uses: ./.github/actions/setup-nix
      with:
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        tools: docs.linkcheck.bin
    - run: postgrest-docs-linkcheck

  on-linkcheck-fail:
    runs-on: ubuntu-latest
    needs: linkcheck
    if: ${{ always() && needs.linkcheck.result == 'failure' }}
    steps:
    - name: Notify on linkcheck failure by commenting
      uses: peter-evans/create-or-update-comment@v4
      with:
        issue-number: 4106
        body: |
          ❌ **Linkcheck Job Failed!**
